version: '3.7'

services:
  nest: 
    image: test:1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    command: npm run test:e2e
    networks:
      - postgres
    env_file:
      - .env

  redis: 
    image: redis:7.0-rc1-alpine3.15
    restart: always
    ports:
      - '6379:6379'
    networks:
      - postgres
    
networks:
  postgres:
    driver: bridge

volumes:
  postgres: 